export type CityTarget = {
    slug: string;
    name: string;
    state: string;
    hubType: "tier1" | "tier2" | "hub";
};

// export const CITY_TARGETS: CityTarget[] = [
//     { slug: "delhi", name: "Delhi", state: "Delhi", hubType: "tier1" },
//     { slug: "mumbai", name: "Mumbai", state: "Maharashtra", hubType: "tier1" },
//     { slug: "bangalore", name: "Bangalore", state: "Karnataka", hubType: "tier1" },
//     { slug: "hyderabad", name: "Hyderabad", state: "Telangana", hubType: "tier1" },
//     { slug: "chennai", name: "Chennai", state: "Tamil Nadu", hubType: "tier1" },
//     { slug: "pune", name: "Pune", state: "Maharashtra", hubType: "tier1" },
//     { slug: "kolkata", name: "Kolkata", state: "West Bengal", hubType: "tier1" },
//     { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat", hubType: "tier1" },
//     { slug: "jaipur", name: "Jaipur", state: "Rajasthan", hubType: "tier2" },
//     { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh", hubType: "tier2" },
//     { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh", hubType: "tier2" },
//     { slug: "nagpur", name: "Nagpur", state: "Maharashtra", hubType: "tier2" },
//     { slug: "indore", name: "Indore", state: "Madhya Pradesh", hubType: "tier2" },
//     { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh", hubType: "tier2" },
//     { slug: "patna", name: "Patna", state: "Bihar", hubType: "tier2" },
//     { slug: "chandigarh", name: "Chandigarh", state: "Chandigarh", hubType: "tier2" },
//     { slug: "surat", name: "Surat", state: "Gujarat", hubType: "tier2" },
//     { slug: "kota", name: "Kota", state: "Rajasthan", hubType: "hub" },
//     { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu", hubType: "tier2" },
//     { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh", hubType: "tier2" },
//     { slug: "thane", name: "Thane", state: "Maharashtra", hubType: "tier2" },
//     { slug: "nashik", name: "Nashik", state: "Maharashtra", hubType: "tier2" },
//     { slug: "vadodara", name: "Vadodara", state: "Gujarat", hubType: "tier2" },
//     { slug: "rajkot", name: "Rajkot", state: "Gujarat", hubType: "tier2" },
//     { slug: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh", hubType: "tier2" },
//     { slug: "guwahati", name: "Guwahati", state: "Assam", hubType: "tier2" },
//     { slug: "amritsar", name: "Amritsar", state: "Punjab", hubType: "tier2" },
//     { slug: "agra", name: "Agra", state: "Uttar Pradesh", hubType: "tier2" },
//     { slug: "meerut", name: "Meerut", state: "Uttar Pradesh", hubType: "tier2" },
//     { slug: "ranchi", name: "Ranchi", state: "Jharkhand", hubType: "tier2" },
//     { slug: "raipur", name: "Raipur", state: "Chhattisgarh", hubType: "tier2" },
//     { slug: "ludhiana", name: "Ludhiana", state: "Punjab", hubType: "tier2" },
//     { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra", hubType: "tier2" },
//     { slug: "mysore", name: "Mysore", state: "Karnataka", hubType: "tier2" },
//     { slug: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh", hubType: "tier2" },
//     { slug: "madurai", name: "Madurai", state: "Tamil Nadu", hubType: "tier2" },
//     { slug: "kochi", name: "Kochi", state: "Kerala", hubType: "tier2" },
//     { slug: "kozhikode", name: "Kozhikode", state: "Kerala", hubType: "tier2" },
//     { slug: "thiruvananthapuram", name: "Thiruvananthapuram", state: "Kerala", hubType: "tier2" },
//     { slug: "dehradun", name: "Dehradun", state: "Uttarakhand", hubType: "hub" },
//     { slug: "noida", name: "Noida", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "gurgaon", name: "Gurgaon", state: "Haryana", hubType: "hub" },
//     { slug: "faridabad", name: "Faridabad", state: "Haryana", hubType: "hub" },
//     { slug: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "jodhpur", name: "Jodhpur", state: "Rajasthan", hubType: "hub" },
//     { slug: "udaipur", name: "Udaipur", state: "Rajasthan", hubType: "hub" },
//     { slug: "ajmer", name: "Ajmer", state: "Rajasthan", hubType: "hub" },
//     { slug: "sikar", name: "Sikar", state: "Rajasthan", hubType: "hub" },
//     { slug: "alwar", name: "Alwar", state: "Rajasthan", hubType: "hub" },
//     { slug: "gwalior", name: "Gwalior", state: "Madhya Pradesh", hubType: "hub" },
//     { slug: "ujjain", name: "Ujjain", state: "Madhya Pradesh", hubType: "hub" },
//     { slug: "sagar", name: "Sagar", state: "Madhya Pradesh", hubType: "hub" },
//     { slug: "bilaspur", name: "Bilaspur", state: "Chhattisgarh", hubType: "hub" },
//     { slug: "durg", name: "Durg", state: "Chhattisgarh", hubType: "hub" },
//     { slug: "bhilai", name: "Bhilai", state: "Chhattisgarh", hubType: "hub" },
//     { slug: "jamshedpur", name: "Jamshedpur", state: "Jharkhand", hubType: "hub" },
//     { slug: "dhanbad", name: "Dhanbad", state: "Jharkhand", hubType: "hub" },
//     { slug: "bokaro", name: "Bokaro", state: "Jharkhand", hubType: "hub" },
//     { slug: "muzaffarpur", name: "Muzaffarpur", state: "Bihar", hubType: "hub" },
//     { slug: "gaya", name: "Gaya", state: "Bihar", hubType: "hub" },
//     { slug: "darbhanga", name: "Darbhanga", state: "Bihar", hubType: "hub" },
//     { slug: "bhagalpur", name: "Bhagalpur", state: "Bihar", hubType: "hub" },
//     { slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "prayagraj", name: "Prayagraj", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "aligarh", name: "Aligarh", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "mathura", name: "Mathura", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "gorakhpur", name: "Gorakhpur", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "bareilly", name: "Bareilly", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "moradabad", name: "Moradabad", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "saharanpur", name: "Saharanpur", state: "Uttar Pradesh", hubType: "hub" },
//     { slug: "roorkee", name: "Roorkee", state: "Uttarakhand", hubType: "hub" },
//     { slug: "haridwar", name: "Haridwar", state: "Uttarakhand", hubType: "hub" },
//     { slug: "jammu", name: "Jammu", state: "Jammu and Kashmir", hubType: "hub" },
//     { slug: "srinagar", name: "Srinagar", state: "Jammu and Kashmir", hubType: "hub" },
//     { slug: "shimla", name: "Shimla", state: "Himachal Pradesh", hubType: "hub" },
//     { slug: "panipat", name: "Panipat", state: "Haryana", hubType: "hub" },
//     { slug: "hisar", name: "Hisar", state: "Haryana", hubType: "hub" },
//     { slug: "sonipat", name: "Sonipat", state: "Haryana", hubType: "hub" },
//     { slug: "kurukshetra", name: "Kurukshetra", state: "Haryana", hubType: "hub" },
//     { slug: "patiala", name: "Patiala", state: "Punjab", hubType: "hub" },
//     { slug: "jalandhar", name: "Jalandhar", state: "Punjab", hubType: "hub" },
//     { slug: "bathinda", name: "Bathinda", state: "Punjab", hubType: "hub" },
//     { slug: "pathankot", name: "Pathankot", state: "Punjab", hubType: "hub" },
//     { slug: "bhubaneswar", name: "Bhubaneswar", state: "Odisha", hubType: "hub" },
//     { slug: "cuttack", name: "Cuttack", state: "Odisha", hubType: "hub" },
//     { slug: "rourkela", name: "Rourkela", state: "Odisha", hubType: "hub" },
//     { slug: "sambalpur", name: "Sambalpur", state: "Odisha", hubType: "hub" },
//     { slug: "puri", name: "Puri", state: "Odisha", hubType: "hub" },
//     { slug: "warangal", name: "Warangal", state: "Telangana", hubType: "hub" },
//     { slug: "tirupati", name: "Tirupati", state: "Andhra Pradesh", hubType: "hub" },
//     { slug: "guntur", name: "Guntur", state: "Andhra Pradesh", hubType: "hub" },
//     { slug: "kakinada", name: "Kakinada", state: "Andhra Pradesh", hubType: "hub" },
//     { slug: "rajahmundry", name: "Rajahmundry", state: "Andhra Pradesh", hubType: "hub" },
//     { slug: "salem", name: "Salem", state: "Tamil Nadu", hubType: "hub" },
//     { slug: "tirunelveli", name: "Tirunelveli", state: "Tamil Nadu", hubType: "hub" },
//     { slug: "trichy", name: "Trichy", state: "Tamil Nadu", hubType: "hub" },
//     { slug: "vellore", name: "Vellore", state: "Tamil Nadu", hubType: "hub" },
//     { slug: "erode", name: "Erode", state: "Tamil Nadu", hubType: "hub" },
//     { slug: "belgaum", name: "Belgaum", state: "Karnataka", hubType: "hub" },
//     { slug: "gulbarga", name: "Gulbarga", state: "Karnataka", hubType: "hub" },
//     { slug: "davangere", name: "Davangere", state: "Karnataka", hubType: "hub" },
//     { slug: "tumkur", name: "Tumkur", state: "Karnataka", hubType: "hub" },
//     { slug: "hubli", name: "Hubli", state: "Karnataka", hubType: "hub" },
//     { slug: "kolhapur", name: "Kolhapur", state: "Maharashtra", hubType: "hub" },
//     { slug: "solapur", name: "Solapur", state: "Maharashtra", hubType: "hub" },
//     { slug: "amravati", name: "Amravati", state: "Maharashtra", hubType: "hub" },
//     { slug: "sangli", name: "Sangli", state: "Maharashtra", hubType: "hub" },
//     { slug: "akola", name: "Akola", state: "Maharashtra", hubType: "hub" },
// ];

export const FEATURE_DEEP_DIVE_SLUGS = [
    "lead-management",
    "student-records",
    "fee-management",
    "installment-tracking",
    "student-portal",
    "course-batch-management",
    "admission-pipeline",
    "enquiry-capture",
    "communication-tools",
    "analytics-and-reports",
    "attendance-tracking",
    "exam-management",
    "progress-reports",
    "teacher-management",
    "sms-notifications",
    "mobile-app",
    "online-admissions",
    "fee-reminders",
    "expense-tracking",
    "time-table",
    "library-management",
    "mock-test",
    "parent-app",
    "multi-branch",
    "inventory",
    "payroll",
    "data-security",
    "custom-reports",
    "website-integration",
    "whatsapp-integration",
] as const;

// export const INDUSTRY_PAGE_SLUGS = [
//     "crm-for-jeeneet-coaching",
//     "crm-for-neet-coaching",
//     "crm-for-upsc-coaching",
//     "crm-for-mpsc-coaching",
//     "crm-for-gate-coaching",
//     "crm-for-ssc-coaching",
//     "crm-for-banking-exam-coaching",
//     "crm-for-foundation-course",
//     "crm-for-engineering-coaching",
//     "crm-for-medical-coaching",
//     "crm-for-commerce-coaching",
//     "crm-for-language-classes",
//     "crm-for-competitive-exams",
//     "crm-for-cat-coaching",
//     "crm-for-clat-coaching",
//     "crm-for-ca-cs-coaching",
//     "crm-for-ielts-coaching",
//     "crm-for-pte-coaching",
//     "crm-for-spoken-english",
//     "crm-for-kids-coaching",
// ] as const;

// export const PROBLEM_PAGE_SLUGS = [
//     "track-coaching-enquiries",
//     "manage-student-admissions",
//     "automate-fee-collection",
//     "reduce-student-dropouts",
//     "manage-coaching-operations",
//     "handle-batch-conflicts",
//     "improve-parent-communication",
//     "digitize-student-records",
//     "why-coaching-needs-crm",
//     "problems-with-manual-admission-process",
//     "increase-coaching-enrollments",
//     "stop-manual-data-entry",
//     "track-coaching-finances",
//     "manage-study-material",
//     "conduct-online-tests",
//     "improve-student-performance",
//     "automate-followups",
//     "handle-peak-admissions",
//     "manage-multiple-branches",
//     "build-coaching-sales-pipeline",
// ] as const;

export function titleFromSlug(slug: string): string {
    return slug
        .replace(/-/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase())
        .replace("Crm", "CRM")
        .replace("Jee", "JEE")
        .replace("Neet", "NEET")
        .replace("Upsc", "UPSC")
        .replace("Mpsc", "MPSC")
        .replace("Ssc", "SSC")
        .replace("Cat", "CAT")
        .replace("Clat", "CLAT")
        .replace("Ielts", "IELTS")
        .replace("Pte", "PTE")
        .replace("Ca", "CA")
        .replace("Cs", "CS");
}
