const ROUTES = {
	ROOT: "/",
	HOME: "/",
	DASHBOARD: {
		ROOT: "/overview",
		LEADS: "/leads",
		STUDENTS: "/students",
		TEAM: "/team",
		COURSES: "/courses",
		BATCHES: "/batches",
		FEES: "/fees",
		PAYMENTS: "/payments",
		DEFAULTERS: "/defaulters",
		TEACHERS: "/teachers",
		UPLOAD: "/upload",
		INTEGRATIONS: "/integrations",
		INSTITUTE: "/institute",
		SETTINGS: "/settings",
		BILLING: "/billing",
		BILLING_PAYMENTS: "/billing/payments",
		BILLING_PAYMENT_DETAILS: "/billing/payment-details",
		BILLING_PLANS: "/billing/plans",
		PROFILE: "/profile",
		PUBLIC_INSTITUTE: (slug: string) => `/i/${slug}`,
	},
	AUTH: {
		LOG_IN: "/login",
		SIGN_UP: "/signup",
		VERIFICATION: "/verification",
	},
	PRICING: "/pricing",
	FEATURES: "/features",
	FEATURE_DETAILS: {
		LEAD_MANAGEMENT: "/features/lead-management",
		STUDENT_RECORDS: "/features/student-records",
		PUBLIC_INSTITUTE_PAGE: "/features/public-institute-page",
		SUBSCRIPTION_BILLING: "/features/subscription-billing",
	},
	USE_CASES: "/use-cases",
	RESOURCES: "/resources",
	HELP: "/help",
	INSTITUTES: "/institutes",
	TOOLS: "/tools",
	DEMO_INSTITUTE: "/demo-institute",
	ABOUT: "/about",
	CONTACT: "/contact",
	SECURITY: "/security",
	PRIVACY: "/privacy",
	TERMS: "/terms",
};

export default ROUTES;
